baseURL = "https://cctv-bogor.online/"
languageCode = "id"
title = "Jasa Pasang Kamera CCTV Bogor | Solusi Keamanan Terpercaya untuk Rumah & Bisnis"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jasa Pasang Kamera CCTV Bogor | Solusi Keamanan Terpercaya untuk Rumah & Bisnis"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/logo-cctv-bogor.png"
  logo_amp = "/images/logo/cctv-bogor-512x512.png"
  footer_logo = "/images/logo/logo-cctv-bogor-putih.png"
  favicon = "/images/logo/cctv-bogor-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "Kang. Mul"
  telepon = "//+6289686868868"
  whatsapp = "//api.whatsapp.com/send?phone=6289686868868&text=*Halo cctv-bogor.online*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

# Schema settings
base_price = 150000
price_range = 2550000
categories = ["Jasa Pasang CCTV", "CCTV Rumah", "CCTV Kantor", "CCTV Sekolah", "CCTV Outdoor", "CCTV Indoor"]
payment_methods = ["COD (Bayar di Tempat)", "Transfer Bank", "DP 30%", "Bayar Setelah Instalasi", "Bayar Bertahap"]
area_served = ["Bogor", "Jakarta", "Depok", "Tangerang", "Bekasi", "Cibinong", "Sentul", "Cileungsi", "Parung", "Cisarua", "Sukabumi"]
keywords = ["jasa pasang cctv bogor", "pasang kamera cctv rumah", "instalasi cctv kantor", "paket cctv murah", "cctv online", "cctv wireless", "cctv terbaik bogor"]
free_shipping = true

# Product
materials = [
  "Kamera CCTV Hikvision Turbo HD Outdoor 2.0 MP",
  "NEXTCAM New Osaka HD Kamera CCTV",
  "Kamera CCTV indoor 5 MP",
  "DVR 4 Port lengkap",
  "Hardisk khusus CCTV Purple",
  "Kabel RG-59",
  "Power Supply CCTV",
  "BNC Drat RG-59"
]
return_policies = [
  "Garansi pemasangan 1 tahun.",
  "Penggantian unit jika rusak dalam masa garansi.",
  "Gratis pengecekan ulang jika instalasi bermasalah."
]

# Service
service_types = [
  "Pemasangan CCTV Rumah",
  "Pemasangan CCTV Kantor",
  "Pemasangan CCTV Sekolah",
  "Pemasangan CCTV Outdoor & Indoor",
  "Maintenance & Perbaikan CCTV"
]
cancellation_policies = [
  "Pembatalan sebelum pemasangan tanpa biaya.",
  "Pengembalian DP jika pemasangan tidak jadi.",
  "Revisi posisi kamera tanpa biaya tambahan saat instalasi."
]
service_output = "Keamanan rumah & bisnis Anda terpantau 24 jam dengan pemasangan CCTV profesional dan bergaransi."

# Informasi Perusahaan
companyName = "CV. CCTV Bogor Online"
aboutUs = "Kami adalah spesialis jasa pemasangan kamera CCTV di Bogor dan sekitarnya, menyediakan solusi keamanan terbaik untuk rumah, kantor, sekolah, dan area bisnis dengan produk berkualitas dan teknisi berpengalaman."
companyWeb = "cctv-bogor.online"

# Informasi Kontak
phone = "0896-8686-8868"
email = "tukangpasangcctvbogor@gmail.com"
address = "Jl. Raya Cibinong No. 123, Bogor, Jawa Barat 16710"
whatsappNumber = "6289686868868"

 # Hero Section
hero_image = "/images/admin/bg_brc_gelap.png"
hero_title = "Jasa Pasang Kamera CCTV Bogor"
hero_description = "Solusi pemasangan CCTV profesional untuk rumah, kantor, sekolah, dan bisnis Anda di Bogor. Keamanan terjamin dengan produk berkualitas dan teknisi berpengalaman."
hero_cta_text = "Lihat Paket CCTV"
services_cta_text = "Konsultasi Gratis"

# Gallery Images
gallery_images = [
  "/images/gallery/installation/pemasangan-cctv-1.jpg",
  "/images/gallery/installation/pemasangan-cctv-2.jpg", 
  "/images/gallery/installation/pemasangan-cctv-3.jpg",
  "/images/gallery/installation/pemasangan-cctv-4.jpg"
]

# Footer Section
footer_about_title = "Mengapa Pilih Kami?"
footer_about_description = "Kami menyediakan layanan pemasangan CCTV terbaik di Bogor dengan harga terjangkau, garansi pemasangan, dan dukungan teknis profesional untuk keamanan properti Anda."

footer_services_title = "Layanan Kami"
footer_contact_title = "Kontak Kami"
footer_bottom_text = "@2025 CCTV Bogor Online. Hak Cipta Dilindungi."

# Testimonials Section
testimonials_title = "Pendapat Klien Kami"

[[params.footer_services]]
text = "cctv-bogor.online adalah layanan spesialis pemasangan kamera CCTV profesional di Bogor dan sekitarnya. Kami menyediakan solusi keamanan terbaik untuk rumah, kantor, sekolah, dan bisnis Anda dengan produk CCTV berkualitas, teknisi berpengalaman, harga terjangkau, serta garansi pemasangan. Percayakan keamanan properti Anda kepada kami untuk hasil yang optimal dan layanan purna jual terpercaya."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jl. Raya Cibinong No. 123, Bogor, Jawa Barat 16710"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "0896-8686-8868"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "tukangpasangcctvbogor@gmail.com"

# Product Features
[[params.product_features]]
icon = "fas fa-shield-alt"
title = "Keamanan 24/7"
description = "Pemantauan keamanan non-stop dengan kualitas gambar HD"

[[params.product_features]]
icon = "fas fa-cogs"
title = "Instalasi Profesional"
description = "Tim teknisi berpengalaman dan tersertifikasi"

[[params.product_features]]
icon = "fas fa-mobile-alt"
title = "Akses Mobile"
description = "Pantau kamera dari smartphone kapanpun & dimanapun"

# Product Types
[[params.product_types]]
image = "/images/products/indoor/cctv-indoor.jpg"
name = "CCTV Indoor 5 MP"
description = "Kamera pengawas indoor 5MP dengan night vision"
price = "Rp 550.000 - Rp 1.000.000"
link = "/products/cctv-indoor"

[[params.product_types]]
image = "/images/products/outdoor/cctv-outdoor.jpg"
name = "NEXTCAM New Osaka HD"
description = "Kamera CCTV outdoor tahan cuaca"
price = "Rp 300.000 - Rp 550.000"
link = "/products/cctv-outdoor"

# Profile Info
profile_photo = "/images/team/staff/owner.jpg"
owner_name = "Budi Santoso"
owner_position = "CEO & Founder"
owner_bio = "Berpengalaman lebih dari 10 tahun dalam industri keamanan CCTV"
owner_social = [
  {platform = "Facebook", url = "#", icon = "fab fa-facebook"},
  {platform = "Instagram", url = "#", icon = "fab fa-instagram"}
]

[[params.testimonials]]
avatar = "/images/admin/avatar1.png"
name = "Budi"
message = "Saya menggunakan jasa pemasangan CCTV dari cctv-bogor.online untuk rumah saya. Proses pemasangan sangat cepat, teknisinya ramah dan profesional. Hasil gambar kameranya jernih dan area rumah jadi lebih aman."
response = "Terima kasih Pak Budi atas kepercayaannya menggunakan layanan kami. Kami senang bisa membantu meningkatkan keamanan rumah Anda."
rating = 5

[[params.testimonials]]
avatar = "/images/admin/avatar2.png"
name = "Siti"
message = "Pelayanan pemasangan CCTV di kantor kami sangat memuaskan. Konsultasi gratis, harga transparan, dan pemasangan rapi. Sekarang kantor jadi lebih tenang karena semua area terpantau."
response = "Terima kasih Ibu Siti atas ulasannya. Kami selalu berusaha memberikan layanan terbaik untuk setiap pelanggan."
rating = 5

[[params.testimonials]]
avatar = "/images/admin/avatar3.png"
name = "Joko"
message = "Saya pesan paket CCTV untuk toko. Proses survei dan pemasangan cepat, hasilnya sesuai harapan. Ada garansi pemasangan juga, jadi makin yakin."
response = "Terima kasih Pak Joko sudah mempercayakan pemasangan CCTV pada kami. Semoga toko Bapak selalu aman."
rating = 4

[[params.testimonials]]
avatar = "/images/admin/avatar4.png"
name = "Dewi"
message = "Teknisi cctv-bogor.online sangat membantu, penjelasannya jelas dan pemasangan tidak mengganggu aktivitas di rumah. Hasil pemasangan rapi dan bisa dipantau lewat HP."
response = "Terima kasih Ibu Dewi atas feedbacknya. Kami senang bisa memberikan solusi keamanan yang praktis untuk keluarga Anda."
rating = 5

[[params.testimonials]]
avatar = "/images/admin/avatar5.png"
name = "Agus"
message = "Harga paket CCTV di sini sangat terjangkau dan kualitas kameranya bagus. Proses pemasangan juga cepat dan bersih. Sangat direkomendasikan!"
response = "Terima kasih Pak Agus atas rekomendasinya. Kami selalu berkomitmen memberikan layanan terbaik dan harga bersaing."
rating = 5

[[params.testimonials]]
avatar = "/images/admin/avatar6.png"
name = "Rina"
message = "Saya pasang CCTV untuk sekolah. Pelayanan dari awal konsultasi sampai pemasangan sangat profesional. Semua area sekolah sekarang bisa dipantau dengan jelas."
response = "Terima kasih Ibu Rina atas kepercayaannya. Semoga sistem CCTV kami bisa membantu meningkatkan keamanan di sekolah."
rating = 5

[[params.tabelItems]]
  name = "Jasa Pasang CCTV (1-5 titik)"
  price = "Rp150.000 - Rp400.000"
[[params.tabelItems]]
  name = "Instalasi IP CCTV Full HD (>10 titik)"
  price = "Rp100.000 - Rp500.000"
[[params.tabelItems]]
  name = "Pemasangan kamera CCTV (indoor & outdoor)"
  price = "Rp70.000 - Rp230.000"
[[params.tabelItems]]
  name = "Pemasangan konektor BNC CCTV"
  price = "Rp55.000 - Rp140.000"
[[params.tabelItems]]
  name = "Setting DVR dan HP online"
  price = "Rp150.000 - Rp250.000"

[[params.tabelItems]]
  name = "NEXTCAM New Osaka HD Kamera CCTV"
  price = "Rp300.000 - Rp550.000"
[[params.tabelItems]]
  name = "Kamera CCTV indoor 5 MP"
  price = "Rp550.000 - Rp1.000.000"
[[params.tabelItems]]
  name = "DVR 4 Port lengkap"
  price = "Rp850.000 - Rp2.550.000"
[[params.tabelItems]]
  name = "BNC Drat RG-59"
  price = "Rp65.000 - Rp90.000"
[[params.tabelItems]]
  name = "Power DC 12 Volt"
  price = "Rp250.000 - Rp550.000"

[[params.tabelItems]]
  name = "Power Supply Box CCTV [12 V/10A/9 Channels]"
  price = "Rp250.000 - Rp450.000"
[[params.tabelItems]]
  name = "Power Supply CCTV / Lampu LED [DC12V10A]"
  price = "Rp110.000 - Rp350.000"

[params.appliList]
  "Jasa Pasang CCTV (1-5 titik)" = "Cocok untuk rumah kecil, toko, atau area terbatas"
  "Instalasi IP CCTV Full HD (>10 titik)" = "Ideal untuk kantor besar, sekolah, atau area bisnis luas"
  "Pemasangan kamera CCTV (indoor & outdoor)" = "Untuk pemasangan individual kamera indoor atau outdoor"
  "Pemasangan konektor BNC CCTV" = "Pemasangan konektor untuk kabel CCTV sistem analog"
  "Setting DVR dan HP online" = "Konfigurasi sistem agar bisa dipantau via smartphone"
  "NEXTCAM New Osaka HD Kamera CCTV" = "Kamera CCTV kualitas HD untuk kebutuhan umum"
  "Kamera CCTV indoor 5 MP" = "Kamera indoor resolusi tinggi untuk detail gambar yang jernih"
  "DVR 4 Port lengkap" = "Sistem perekam untuk 4 kamera CCTV dengan storage"
  "BNC Drat RG-59" = "Konektor untuk sambungan kabel CCTV sistem analog"
  "Power DC 12 Volt" = "Catu daya untuk sistem CCTV 12V"
  "Power Supply Box CCTV [12 V/10A/9 Channels]" = "Power supply untuk multi kamera hingga 9 channel"
  "Power Supply CCTV / Lampu LED [DC12V10A]" = "Adaptor daya untuk CCTV atau lampu LED 12V"

[params.kegunaanList]
  "Jasa Pasang CCTV (1-5 titik)" = "Mengawasi area utama rumah atau toko dengan budget terjangkau"
  "Instalasi IP CCTV Full HD (>10 titik)" = "Pengawasan menyeluruh area luas dengan kualitas Full HD"
  "Pemasangan kamera CCTV (indoor & outdoor)" = "Pemasangan profesional untuk kamera tunggal"
  "Pemasangan konektor BNC CCTV" = "Memastikan koneksi kabel CCTV yang stabil dan berkualitas"
  "Setting DVR dan HP online" = "Memungkinkan monitoring real-time dari smartphone"
  "NEXTCAM New Osaka HD Kamera CCTV" = "Memberikan gambar HD untuk keamanan standar"
  "Kamera CCTV indoor 5 MP" = "Menghasilkan rekaman sangat detail untuk area dalam ruangan"
  "DVR 4 Port lengkap" = "Merekam dan menyimpan footage dari 4 kamera sekaligus"
  "BNC Drat RG-59" = "Menghubungkan kamera ke DVR dengan koneksi yang kuat"
  "Power DC 12 Volt" = "Memberikan daya stabil untuk operasional kamera CCTV"
  "Power Supply Box CCTV [12 V/10A/9 Channels]" = "Menyuplai daya untuk sistem multi kamera"
  "Power Supply CCTV / Lampu LED [DC12V10A]" = "Memberikan daya untuk kamera atau penerangan tambahan"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "/profile/"

  [[params.menu_items]]
    title = "Biaya"
    url = "/categories/biaya/"

  [[params.menu_items]]
    title = "Jasa"
    url = "/categories/jasa/"

  [[params.menu_items]]
    title = "Info"
    url = "/categories/pasang/"

[params.header]
   title = "Jasa Pasang Kamera CCTV Solusi Keamanan Terpercaya untuk Rumah & Bisnis | "
   highlight = "CCTV Bogor Online"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"